//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'filesDataService';
    angular.module('app').service(serviceId, ['$http', filesDataService]);

    function filesDataService($http) {
        var urlBase = '/api/files';            

        this.getData = function () {
            return $http.get(urlBase  + '/all');
        };

         this.updateFiles = function(files) {
            return $http.put(urlBase, files);
        };

         this.insertFiles = function(files) {
            return $http.post(urlBase, files);
        };

         this.deleteFiles = function(fileID) {
            return $http.Delete(urlBase, fileID);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) { 
            return $http({
                 url: urlBase ,
                 method: 'GET',
                 params: {
                     sortExpression : sortExpression || '', 
                     page : page || '', 
                     pageSize : pageSize || ''
                 }
            });
        };

        this.getDataByFileID = function (fileID) {
            return $http.get(urlBase  + '/all');
        };

        this.getDataByIssueID = function (issueID) {
            return $http.get('/api/issues/' + issueID + '/files/all');
        };

        this.getDataByIssueIDPageable = function (issueID, sortExpression, page, pageSize) { 
            return $http({
                 url: '/api/issues/' + issueID + '/files',
                 method: 'GET',
                 params: {
                     issueID : issueID || '', 
                     sortExpression : sortExpression || '', 
                     page : page || '', 
                     pageSize : pageSize || ''
                 }
            });
        };


    }
})();
