//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'issueHistoryDataService';
    angular.module('app').service(serviceId, ['$http', issueHistoryDataService]);

    function issueHistoryDataService($http) {
        var urlBase = '/api/issueHistories';            

        this.getData = function () {
            return $http.get(urlBase  + '/all');
        };

         this.updateIssueHistory = function(issueHistory) {
            return $http.put(urlBase, issueHistory);
        };

         this.insertIssueHistory = function(issueHistory) {
            return $http.post(urlBase, issueHistory);
        };

         this.deleteIssueHistory = function(issueHistoryID) {
            return $http.Delete(urlBase, issueHistoryID);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) { 
            return $http({
                 url: urlBase ,
                 method: 'GET',
                 params: {
                     sortExpression : sortExpression || '', 
                     page : page || '', 
                     pageSize : pageSize || ''
                 }
            });
        };

        this.getDataByIssueHistoryID = function (issueHistoryID) {
            return $http.get(urlBase  + '/all');
        };


    }
})();
