//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'issueTypesDataService';
    angular.module('app').service(serviceId, ['$http', issueTypesDataService]);

    function issueTypesDataService($http) {
        var urlBase = '/api/issueTypes';            

        this.getData = function () {
            return $http.get(urlBase  + '/all');
        };

         this.updateIssueTypes = function(issueTypes) {
            return $http.put(urlBase, issueTypes);
        };

         this.insertIssueTypes = function(issueTypes) {
            return $http.post(urlBase, issueTypes);
        };

         this.deleteIssueTypes = function(issueTypeID) {
            return $http.Delete(urlBase, issueTypeID);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) { 
            return $http({
                 url: urlBase ,
                 method: 'GET',
                 params: {
                     sortExpression : sortExpression || '', 
                     page : page || '', 
                     pageSize : pageSize || ''
                 }
            });
        };

        this.getDataByIssueTypeID = function (issueTypeID) {
            return $http.get(urlBase + '/' + issueTypeID);
        };


    }
})();
