//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'platformsDataService';
    angular.module('app').service(serviceId, ['$http', platformsDataService]);

    function platformsDataService($http) {
        var urlBase = '/api/platforms';            

        this.getData = function () {
            return $http.get(urlBase  + '/all');
        };

         this.updatePlatforms = function(platforms) {
            return $http.put(urlBase, platforms);
        };

         this.insertPlatforms = function(platforms) {
            return $http.post(urlBase, platforms);
        };

         this.deletePlatforms = function(platformID) {
            return $http.Delete(urlBase, platformID);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) { 
            return $http({
                 url: urlBase ,
                 method: 'GET',
                 params: {
                     sortExpression : sortExpression || '', 
                     page : page || '', 
                     pageSize : pageSize || ''
                 }
            });
        };

        this.getDataByPlatformID = function (platformID) {
            return $http.get(urlBase + '/' + platformID);
        };


    }
})();
