//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'securityQuestionsDataService';
    angular.module('app').service(serviceId, ['$http', securityQuestionsDataService]);

    function securityQuestionsDataService($http) {
        var urlBase = '/api/securityQuestions';            

        this.getData = function () {
            return $http.get(urlBase  + '/all');
        };

         this.updateSecurityQuestions = function(securityQuestions) {
            return $http.put(urlBase, securityQuestions);
        };

         this.insertSecurityQuestions = function(securityQuestions) {
            return $http.post(urlBase, securityQuestions);
        };

         this.deleteSecurityQuestions = function(passwordQuestion) {
            return $http.Delete(urlBase, passwordQuestion);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) { 
            return $http({
                 url: urlBase ,
                 method: 'GET',
                 params: {
                     sortExpression : sortExpression || '', 
                     page : page || '', 
                     pageSize : pageSize || ''
                 }
            });
        };

        this.getDataByPasswordQuestion = function (passwordQuestion) {
            return $http.get(urlBase + '/' + passwordQuestion);
        };


    }
})();
