//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'statusesDataService';
    angular.module('app').service(serviceId, ['$http', statusesDataService]);

    function statusesDataService($http) {
        var urlBase = '/api/statuses';            

        this.getData = function () {
            return $http.get(urlBase  + '/all');
        };

         this.updateStatuses = function(statuses) {
            return $http.put(urlBase, statuses);
        };

         this.insertStatuses = function(statuses) {
            return $http.post(urlBase, statuses);
        };

         this.deleteStatuses = function(statusID) {
            return $http.Delete(urlBase, statusID);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) { 
            return $http({
                 url: urlBase ,
                 method: 'GET',
                 params: {
                     sortExpression : sortExpression || '', 
                     page : page || '', 
                     pageSize : pageSize || ''
                 }
            });
        };

        this.getDataByStatusID = function (statusID) {
            return $http.get(urlBase + '/' + statusID);
        };


    }
})();
