'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Data.Common
Imports System.Data.SqlClient
Imports IssueVision.Data.DbCommandProvider

Namespace IssueVision.Data.SqlDbCommandProvider 

  
Public Class SqlDbSecurityQuestionsCommandProvider
      Implements IDbSecurityQuestionsCommandProvider
    
      ReadOnly _dbConnHolder As DbConnectionHolder

      Public Sub New()
          _dbConnHolder = New DbConnectionHolder(DbConnectionName)
      End Sub

      Public ReadOnly Property DbConnectionName() As String Implements IDbSecurityQuestionsCommandProvider.DbConnectionName
          Get
              Return "IssueVisionConnection"
          End Get
      End Property

      Public ReadOnly Property SecurityQuestionsDbConnectionHolder() As DbConnectionHolder Implements IDbSecurityQuestionsCommandProvider.SecurityQuestionsDbConnectionHolder
          Get
              Return _dbConnHolder
          End Get
      End Property
      
    
        ''' <summary>
        ''' Selects one or more records from the SecurityQuestions table 
        ''' </summary>
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataDbCommand() As IDbCommand Implements IDbSecurityQuestionsCommandProvider.GetGetDataDbCommand
            
            Dim command As New SqlCommand("SecurityQuestions_Select")
            command.CommandType = CommandType.StoredProcedure
    
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Updates one or more records from the SecurityQuestions table 
        ''' </summary>
      ''' <param name="passwordQuestion" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetUpdateDbCommand( ByVal passwordQuestion As String) As IDbCommand Implements IDbSecurityQuestionsCommandProvider.GetUpdateDbCommand
            
            Dim command As New SqlCommand("SecurityQuestions_Update")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@PasswordQuestion", SqlDbType.nvarchar, passwordQuestion))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Inserts a record into the SecurityQuestions table on the database.
        ''' </summary>
      ''' <param name="passwordQuestion" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetInsertDbCommand( ByVal passwordQuestion As String) As IDbCommand Implements IDbSecurityQuestionsCommandProvider.GetInsertDbCommand
            
            Dim command As New SqlCommand("SecurityQuestions_Insert")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@PasswordQuestion", SqlDbType.nvarchar, passwordQuestion))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Deletes one or more records from the SecurityQuestions table 
        ''' </summary>
      ''' <param name="passwordQuestion" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetDeleteDbCommand( ByVal passwordQuestion As String) As IDbCommand Implements IDbSecurityQuestionsCommandProvider.GetDeleteDbCommand
            
            Dim command As New SqlCommand("SecurityQuestions_Delete")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@PasswordQuestion", SqlDbType.nvarchar, passwordQuestion))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetDataPageable returns a IDataReader populated with a subset of data from SecurityQuestions
        ''' </summary>
      ''' <param name="sortExpression" />
      ''' <param name="page" />
      ''' <param name="pageSize" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataPageableDbCommand( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand Implements IDbSecurityQuestionsCommandProvider.GetGetDataPageableDbCommand
            
            Dim command As New SqlCommand("SecurityQuestions_GetDataPageable")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@sortExpression", SqlDbType.varchar, sortExpression))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@page", SqlDbType.Int, page))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@pageSize", SqlDbType.Int, pageSize))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetRowCount returns the row count for SecurityQuestions
        ''' </summary>
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetRowCountDbCommand() As IDbCommand Implements IDbSecurityQuestionsCommandProvider.GetGetRowCountDbCommand
            
            Dim command As New SqlCommand("SecurityQuestions_GetRowCount")
            command.CommandType = CommandType.StoredProcedure
    
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetDataByPasswordQuestion returns a IDataReader for SecurityQuestions
        ''' </summary>
      ''' <param name="passwordQuestion" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataByPasswordQuestionDbCommand( ByVal passwordQuestion As String) As IDbCommand Implements IDbSecurityQuestionsCommandProvider.GetGetDataByPasswordQuestionDbCommand
            
            Dim command As New SqlCommand("SecurityQuestions_GetDataByPasswordQuestion")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@PasswordQuestion", SqlDbType.nvarchar, passwordQuestion))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
  End Class
 End Namespace
  