'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Data.Common
Imports System.Data.SqlClient
Imports IssueVision.Data.DbCommandProvider

Namespace IssueVision.Data.SqlDbCommandProvider 

  
Public Class SqlDbAttributesCommandProvider
      Implements IDbAttributesCommandProvider
    
      ReadOnly _dbConnHolder As DbConnectionHolder

      Public Sub New()
          _dbConnHolder = New DbConnectionHolder(DbConnectionName)
      End Sub

      Public ReadOnly Property DbConnectionName() As String Implements IDbAttributesCommandProvider.DbConnectionName
          Get
              Return "IssueVisionConnection"
          End Get
      End Property

      Public ReadOnly Property AttributesDbConnectionHolder() As DbConnectionHolder Implements IDbAttributesCommandProvider.AttributesDbConnectionHolder
          Get
              Return _dbConnHolder
          End Get
      End Property
      
    
        ''' <summary>
        ''' Selects one or more records from the Attributes table 
        ''' </summary>
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataDbCommand() As IDbCommand Implements IDbAttributesCommandProvider.GetGetDataDbCommand
            
            Dim command As New SqlCommand("Attributes_Select")
            command.CommandType = CommandType.StoredProcedure
    
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Updates one or more records from the Attributes table 
        ''' </summary>
      ''' <param name="iD" />
      ''' <param name="issueID" />
      ''' <param name="attributeName" />
      ''' <param name="value" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetUpdateDbCommand( ByVal iD As Guid,  ByVal issueID As Int64,  ByVal attributeName As String,  ByVal value As String) As IDbCommand Implements IDbAttributesCommandProvider.GetUpdateDbCommand
            
            Dim command As New SqlCommand("Attributes_Update")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@ID", SqlDbType.uniqueidentifier, iD))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@IssueID", SqlDbType.bigint, issueID))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@AttributeName", SqlDbType.ntext, attributeName))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@Value", SqlDbType.ntext, value))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Inserts a record into the Attributes table on the database.
        ''' </summary>
      ''' <param name="iD" />
      ''' <param name="issueID" />
      ''' <param name="attributeName" />
      ''' <param name="value" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetInsertDbCommand( ByVal iD As Guid,  ByVal issueID As Int64,  ByVal attributeName As String,  ByVal value As String) As IDbCommand Implements IDbAttributesCommandProvider.GetInsertDbCommand
            
            Dim command As New SqlCommand("Attributes_Insert")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@ID", SqlDbType.uniqueidentifier, iD))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@IssueID", SqlDbType.bigint, issueID))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@AttributeName", SqlDbType.ntext, attributeName))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@Value", SqlDbType.ntext, value))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Deletes one or more records from the Attributes table 
        ''' </summary>
      ''' <param name="iD" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetDeleteDbCommand( ByVal iD As Guid) As IDbCommand Implements IDbAttributesCommandProvider.GetDeleteDbCommand
            
            Dim command As New SqlCommand("Attributes_Delete")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@ID", SqlDbType.uniqueidentifier, iD))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetDataPageable returns a IDataReader populated with a subset of data from Attributes
        ''' </summary>
      ''' <param name="sortExpression" />
      ''' <param name="page" />
      ''' <param name="pageSize" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataPageableDbCommand( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand Implements IDbAttributesCommandProvider.GetGetDataPageableDbCommand
            
            Dim command As New SqlCommand("Attributes_GetDataPageable")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@sortExpression", SqlDbType.varchar, sortExpression))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@page", SqlDbType.Int, page))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@pageSize", SqlDbType.Int, pageSize))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetRowCount returns the row count for Attributes
        ''' </summary>
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetRowCountDbCommand() As IDbCommand Implements IDbAttributesCommandProvider.GetGetRowCountDbCommand
            
            Dim command As New SqlCommand("Attributes_GetRowCount")
            command.CommandType = CommandType.StoredProcedure
    
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetDataByID returns a IDataReader for Attributes
        ''' </summary>
      ''' <param name="iD" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataByIDDbCommand( ByVal iD As Guid) As IDbCommand Implements IDbAttributesCommandProvider.GetGetDataByIDDbCommand
            
            Dim command As New SqlCommand("Attributes_GetDataByID")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@ID", SqlDbType.uniqueidentifier, iD))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetDataByIssueID returns a IDataReader for Attributes
        ''' </summary>
      ''' <param name="issueID" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataByIssueIDDbCommand( ByVal issueID As Int64) As IDbCommand Implements IDbAttributesCommandProvider.GetGetDataByIssueIDDbCommand
            
            Dim command As New SqlCommand("Attributes_GetDataByIssueID")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@IssueID", SqlDbType.bigint, issueID))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetDataByIssueIDPageable returns a IDataReader populated with a subset of data from Attributes
        ''' </summary>
      ''' <param name="issueID" />
      ''' <param name="sortExpression" />
      ''' <param name="page" />
      ''' <param name="pageSize" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataByIssueIDPageableDbCommand( ByVal issueID As Int64,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand Implements IDbAttributesCommandProvider.GetGetDataByIssueIDPageableDbCommand
            
            Dim command As New SqlCommand("Attributes_GetDataByIssueIDPageable")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@IssueID", SqlDbType.bigint, issueID))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@sortExpression", SqlDbType.varchar, sortExpression))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@page", SqlDbType.Int, page))
                  command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@pageSize", SqlDbType.Int, pageSize))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
        ''' <summary>
        ''' Function GetRowCount returns the row count for Attributes
        ''' </summary>
      ''' <param name="issueID" />
        ''' <returns></returns>
        ''' <remarks></remarks> 
        Public Function GetGetDataByIssueIDRowCountDbCommand( ByVal issueID As Int64) As IDbCommand Implements IDbAttributesCommandProvider.GetGetDataByIssueIDRowCountDbCommand
            
            Dim command As New SqlCommand("Attributes_GetDataByIssueIDRowCount")
            command.CommandType = CommandType.StoredProcedure
                command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@IssueID", SqlDbType.bigint, issueID))
      
            command.Connection = CType(_dbConnHolder.Connection, SqlConnection)
            Return command
      End Function
         
            
  End Class
 End Namespace
  