'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities

  
 Namespace IssueVision.Data.Repository     
    Public Interface IIssueTypesRepository
        Function GetData()  as ICollection(Of IssueTypes)
        Sub Update( ByVal issueTypeID As Byte,  ByVal name As String) 
        Sub Update(ByVal issueTypes as IssueTypes) 
        Function Insert( ByVal issueTypeID As Byte,  ByVal name As String)  as Byte
        Function Insert(ByVal issueTypes as IssueTypes)  as Byte
        Sub Delete( ByVal issueTypeID As Byte) 
        Sub Delete(ByVal issueTypes as IssueTypes) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of IssueTypes)
        Function GetRowCount()  as Int32
        Function GetDataByIssueTypeID( ByVal issueTypeID As Byte)  as ICollection(Of IssueTypes)
    End Interface 
End NameSpace
  