'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities

  
 Namespace IssueVision.Data.Repository     
    Public Interface IIssueHistoryRepository
        Function GetData()  as ICollection(Of IssueHistory)
        Sub Update( ByVal issueID As Int64,  ByVal title As String,  ByVal statusID As Byte,  ByVal subStatusID As  Nullable(Of Byte) ,  ByVal assignedToID As String,  ByVal issueTypeID As Byte,  ByVal severity As Byte,  ByVal priority As Byte,  ByVal changedByID As String,  ByVal lastChange As DateTime,  ByVal openedDate As DateTime,  ByVal openedByID As String,  ByVal platformID As  Nullable(Of Int32) ,  ByVal resolutionDate As  Nullable(Of DateTime) ,  ByVal resolutionID As  Nullable(Of Byte) ,  ByVal resolvedByID As String,  ByVal description As String,  ByVal reproSteps As String,  ByVal duplicateID As  Nullable(Of Int64) ,  ByVal action As String,  ByVal comment As String,  ByVal dateCreated As DateTime,  ByVal issueHistoryID As Int32) 
        Sub Update(ByVal issueHistory as IssueHistory) 
        Function Insert( ByVal issueID As Int64,  ByVal title As String,  ByVal statusID As Byte,  ByVal subStatusID As  Nullable(Of Byte) ,  ByVal assignedToID As String,  ByVal issueTypeID As Byte,  ByVal severity As Byte,  ByVal priority As Byte,  ByVal changedByID As String,  ByVal lastChange As DateTime,  ByVal openedDate As DateTime,  ByVal openedByID As String,  ByVal platformID As  Nullable(Of Int32) ,  ByVal resolutionDate As  Nullable(Of DateTime) ,  ByVal resolutionID As  Nullable(Of Byte) ,  ByVal resolvedByID As String,  ByVal description As String,  ByVal reproSteps As String,  ByVal duplicateID As  Nullable(Of Int64) ,  ByVal action As String,  ByVal comment As String,  ByVal dateCreated As DateTime)  as Int32
        Function Insert(ByVal issueHistory as IssueHistory)  as Int32
        Sub Delete( ByVal issueHistoryID As Int32) 
        Sub Delete(ByVal issueHistory as IssueHistory) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of IssueHistory)
        Function GetRowCount()  as Int32
        Function GetDataByIssueHistoryID( ByVal issueHistoryID As Int32)  as ICollection(Of IssueHistory)
    End Interface 
End NameSpace
  