'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities

  
 Namespace IssueVision.Data.Repository     
    Public Interface IPlatformsRepository
        Function GetData()  as ICollection(Of Platforms)
        Sub Update( ByVal platformID As Int32,  ByVal browser As String,  ByVal browserVersion As String,  ByVal oS As String,  ByVal oSVersion As String,  ByVal language As String,  ByVal processor As String) 
        Sub Update(ByVal platforms as Platforms) 
        Function Insert( ByVal platformID As Int32,  ByVal browser As String,  ByVal browserVersion As String,  ByVal oS As String,  ByVal oSVersion As String,  ByVal language As String,  ByVal processor As String)  as Int32
        Function Insert(ByVal platforms as Platforms)  as Int32
        Sub Delete( ByVal platformID As Int32) 
        Sub Delete(ByVal platforms as Platforms) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Platforms)
        Function GetRowCount()  as Int32
        Function GetDataByPlatformID( ByVal platformID As Int32)  as ICollection(Of Platforms)
    End Interface 
End NameSpace
  