'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities

  
 Namespace IssueVision.Data.Repository     
    Public Interface IResolutionsRepository
        Function GetData()  as ICollection(Of Resolutions)
        Sub Update( ByVal resolutionID As Byte,  ByVal name As String) 
        Sub Update(ByVal resolutions as Resolutions) 
        Function Insert( ByVal resolutionID As Byte,  ByVal name As String)  as Byte
        Function Insert(ByVal resolutions as Resolutions)  as Byte
        Sub Delete( ByVal resolutionID As Byte) 
        Sub Delete(ByVal resolutions as Resolutions) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Resolutions)
        Function GetRowCount()  as Int32
        Function GetDataByResolutionID( ByVal resolutionID As Byte)  as ICollection(Of Resolutions)
    End Interface 
End NameSpace
  