'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities

  
 Namespace IssueVision.Data.Repository     
    Public Interface ISecurityQuestionsRepository
        Function GetData()  as ICollection(Of SecurityQuestions)
        Sub Update( ByVal passwordQuestion As String) 
        Sub Update(ByVal securityQuestions as SecurityQuestions) 
        Function Insert( ByVal passwordQuestion As String)  as String
        Function Insert(ByVal securityQuestions as SecurityQuestions)  as String
        Sub Delete( ByVal passwordQuestion As String) 
        Sub Delete(ByVal securityQuestions as SecurityQuestions) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of SecurityQuestions)
        Function GetRowCount()  as Int32
        Function GetDataByPasswordQuestion( ByVal passwordQuestion As String)  as ICollection(Of SecurityQuestions)
    End Interface 
End NameSpace
  