'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities

  
 Namespace IssueVision.Data.Repository     
    Public Interface ISubStatusesRepository
        Function GetData()  as ICollection(Of SubStatuses)
        Sub Update( ByVal subStatusId As Byte,  ByVal name As String) 
        Sub Update(ByVal subStatuses as SubStatuses) 
        Function Insert( ByVal subStatusId As Byte,  ByVal name As String)  as Byte
        Function Insert(ByVal subStatuses as SubStatuses)  as Byte
        Sub Delete( ByVal subStatusId As Byte) 
        Sub Delete(ByVal subStatuses as SubStatuses) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of SubStatuses)
        Function GetRowCount()  as Int32
        Function GetDataBySubStatusId( ByVal subStatusId As Byte)  as ICollection(Of SubStatuses)
    End Interface 
End NameSpace
  