'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities

  
 Namespace IssueVision.Data.Repository     
    Public Interface IUsersRepository
        Function GetData()  as ICollection(Of Users)
        Sub Update( ByVal name As String,  ByVal firstName As String,  ByVal lastName As String,  ByVal email As String,  ByVal passwordHash As String,  ByVal passwordSalt As String,  ByVal passwordQuestion As String,  ByVal passwordAnswerHash As String,  ByVal passwordAnswerSalt As String,  ByVal userType As String,  ByVal profileReset As Byte) 
        Sub Update(ByVal users as Users) 
        Function Insert( ByVal name As String,  ByVal firstName As String,  ByVal lastName As String,  ByVal email As String,  ByVal passwordHash As String,  ByVal passwordSalt As String,  ByVal passwordQuestion As String,  ByVal passwordAnswerHash As String,  ByVal passwordAnswerSalt As String,  ByVal userType As String,  ByVal profileReset As Byte)  as String
        Function Insert(ByVal users as Users)  as String
        Sub Delete( ByVal name As String) 
        Sub Delete(ByVal users as Users) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Users)
        Function GetRowCount()  as Int32
        Function GetDataByName( ByVal name As String)  as ICollection(Of Users)
        Function GetDataByPasswordQuestion( ByVal passwordQuestion As String)  as ICollection(Of Users)
        Function GetDataByPasswordQuestionPageable( ByVal passwordQuestion As String,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Users)
        Function GetDataByPasswordQuestionRowCount( ByVal passwordQuestion As String)  as Int32
    End Interface 
End NameSpace
  