USE [IssueVision]
GO

/****** Object:  Table [dbo].[SecurityQuestions] ******/
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'In what city were you married? (Enter full name of city)')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What was the name of your High School?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What is your father''s middle name?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What is your best friend''s first name?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What was your dream job as a child?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'In what city was your high school? (Enter full name of city)')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What is the name of the first company you worked for?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What is your maternal grandmother''s first name?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What is the first name of your oldest nephew?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What is your maternal grandfather''s first name?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What was the first name of your first manager?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What was the name of your first girlfriend/boyfriend?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What was the name of your first pet?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What is the first name of your oldest niece?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'In what city was your father born? (Enter full name of city)')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'In what city is your vacation home? (Enter full name of city)')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What is your paternal grandmother''s first name?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What was the nickname of your grandfather?')
INSERT [dbo].[SecurityQuestions] ([PasswordQuestion]) VALUES (N'What was your high school mascot?')
/****** Object:  Table [dbo].[Users] ******/
INSERT [dbo].[Users] ([Name], [FirstName], [LastName], [Email], [PasswordHash], [PasswordSalt], [PasswordQuestion], [PasswordAnswerHash], [PasswordAnswerSalt], [UserType], [ProfileReset]) VALUES (N'admin1', N'Fred', N'Bloggs', NULL, N'LvnDL3Iy/h2nm1FO2/rD0yrch24sKSrCZpmTv4wQc4PmILDLhgpcfqCgXWi06WyM3Mx2AY93oJzNwVqVrER/rQ==', N'I1nIRw==', N'In what city is your vacation home? (Enter full name of city)', N'teIPQA==', N'X0najw==', N'A', 1)
INSERT [dbo].[Users] ([Name], [FirstName], [LastName], [Email], [PasswordHash], [PasswordSalt], [PasswordQuestion], [PasswordAnswerHash], [PasswordAnswerSalt], [UserType], [ProfileReset]) VALUES (N'user1', N'John', N'Doe', NULL, N'p13yuVCMCIgTy6jOf0ypzUPKWdSkYqcqYJAUwC2WGAOdk9EQD5ciEBD8s8hVPd+i36icrnH4SK+1sWLUQ5ZTpg==', N'qUCPFQ==', N'In what city is your vacation home? (Enter full name of city)', N'kqTjVA==', N'iCQYWA==', N'U', 1)
/****** Object:  Table [dbo].[SubStatuses] ******/
INSERT [dbo].[SubStatuses] ([SubStatusId], [Name]) VALUES (0, N'Blocked')
INSERT [dbo].[SubStatuses] ([SubStatusId], [Name]) VALUES (1, N'Understood')
INSERT [dbo].[SubStatuses] ([SubStatusId], [Name]) VALUES (2, N'Testing fix')
INSERT [dbo].[SubStatuses] ([SubStatusId], [Name]) VALUES (3, N'Fix available')
INSERT [dbo].[SubStatuses] ([SubStatusId], [Name]) VALUES (4, N'Investigating cause')
INSERT [dbo].[SubStatuses] ([SubStatusId], [Name]) VALUES (5, N'Need repro')
INSERT [dbo].[SubStatuses] ([SubStatusId], [Name]) VALUES (6, N'Staging')
INSERT [dbo].[SubStatuses] ([SubStatusId], [Name]) VALUES (7, N'Working on fix')
/****** Object:  Table [dbo].[Statuses] ******/
INSERT [dbo].[Statuses] ([StatusID], [Name]) VALUES (0, N'Open')
INSERT [dbo].[Statuses] ([StatusID], [Name]) VALUES (1, N'Active')
INSERT [dbo].[Statuses] ([StatusID], [Name]) VALUES (2, N'Pending')
INSERT [dbo].[Statuses] ([StatusID], [Name]) VALUES (3, N'Resolved')
/****** Object:  Table [dbo].[Resolutions] ******/
INSERT [dbo].[Resolutions] ([ResolutionID], [Name]) VALUES (0, N'No Resolution')
INSERT [dbo].[Resolutions] ([ResolutionID], [Name]) VALUES (1, N'By Design')
INSERT [dbo].[Resolutions] ([ResolutionID], [Name]) VALUES (2, N'Fixed')
INSERT [dbo].[Resolutions] ([ResolutionID], [Name]) VALUES (3, N'Duplicate')
INSERT [dbo].[Resolutions] ([ResolutionID], [Name]) VALUES (4, N'External')
INSERT [dbo].[Resolutions] ([ResolutionID], [Name]) VALUES (5, N'No Repro')
INSERT [dbo].[Resolutions] ([ResolutionID], [Name]) VALUES (6, N'Postponed')
INSERT [dbo].[Resolutions] ([ResolutionID], [Name]) VALUES (7, N'Won''t Fix')
/****** Object:  Table [dbo].[Platforms] ******/
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (0, N'Internet Explorer', N'8', N'Windows', N'7', N'en-us', N'x86')
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (1, N'Internet Explorer', N'8', N'Windows', N'7', N'en-us', N'x64')
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (2, N'Internet Explorer', N'7', N'Windows', N'Vista', N'en-us', N'x86')
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (3, N'Internet Explorer', N'8', N'Windows', N'Vista', N'en-us', N'x64')
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (4, N'Internet Explorer', N'7', N'Windows', N'Vista', N'en-us', N'x86')
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (5, N'Internet Explorer', N'8', N'Windows', N'Vista', N'en-us', N'x64')
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (6, N'Internet Explorer', N'6', N'Windows', N'XP', N'en-us', N'x86')
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (7, N'Internet Explorer', N'7', N'Windows', N'XP', N'en-us', N'x86')
INSERT [dbo].[Platforms] ([PlatformID], [Browser], [BrowserVersion], [OS], [OSVersion], [Language], [Processor]) VALUES (8, N'Internet Explorer', N'8', N'Windows', N'XP', N'en-us', N'x86')
/****** Object:  Table [dbo].[IssueTypes] ******/
INSERT [dbo].[IssueTypes] ([IssueTypeID], [Name]) VALUES (0, N'Code Defect                                       ')
INSERT [dbo].[IssueTypes] ([IssueTypeID], [Name]) VALUES (1, N'Design Change                                     ')
INSERT [dbo].[IssueTypes] ([IssueTypeID], [Name]) VALUES (2, N'Documentation Issue                               ')
INSERT [dbo].[IssueTypes] ([IssueTypeID], [Name]) VALUES (3, N'Sample Issue                                      ')
INSERT [dbo].[IssueTypes] ([IssueTypeID], [Name]) VALUES (4, N'Spec Issue                                        ')
INSERT [dbo].[IssueTypes] ([IssueTypeID], [Name]) VALUES (5, N'Test Defect                                       ')
INSERT [dbo].[IssueTypes] ([IssueTypeID], [Name]) VALUES (6, N'Work Item                                         ')
INSERT [dbo].[IssueTypes] ([IssueTypeID], [Name]) VALUES (7, N'Tracking         