//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace IssueVision.Domain.Entities
{
    [Serializable()]
    public partial class AttributesList :  Collection<Attributes>
    {
        public Attributes First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class Attributes{
      
        private Guid _iD;
        private Int64 _issueID;
        private String _attributeName;
        private String _value; 
        private Issues _issue;  

      public Attributes() : base()
      {
      }

      public Attributes(Guid iD, Int64 issueID, String attributeName, String value) : base()
      {
          
           _iD = iD;
           _issueID = issueID;
           _attributeName = attributeName;
           _value = value;
      }
  
    
        /// <summary>
        /// Public Property ID
        /// </summary>
        /// <returns>ID as Guid</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Guid ID
        {
            get{return this._iD;}
            set{this._iD = value;}
        }

        /// <summary>
        /// Public Property IssueID
        /// </summary>
        /// <returns>IssueID as Int64</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Int64 IssueID
        {
            get{return this._issueID;}
            set{this._issueID = value;}
        }

        /// <summary>
        /// Public Property AttributeName
        /// </summary>
        /// <returns>AttributeName as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String AttributeName
        {
            get{return this._attributeName;}
            set{this._attributeName = value;}
        }

        /// <summary>
        /// Public Property Value
        /// </summary>
        /// <returns>Value as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Value
        {
            get{return this._value;}
            set{this._value = value;}
        }

        [DataMember()]
        public virtual Issues Issue 
        {
          get { return  _issue;}
          set { _issue = value;}
        }
  
      
    }
 }     
