//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace IssueVision.Domain.Entities
{
    [Serializable()]
    public partial class FilesList :  Collection<Files>
    {
        public Files First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class Files{
      
        private Guid _fileID;
        private Int64 _issueID;
        private String _fileName;
        private byte[] _data; 
        private Issues _issue;  

      public Files() : base()
      {
      }

      public Files(Guid fileID, Int64 issueID, String fileName, byte[] data) : base()
      {
          
           _fileID = fileID;
           _issueID = issueID;
           _fileName = fileName;
           _data = data;
      }
  
    
        /// <summary>
        /// Public Property FileID
        /// </summary>
        /// <returns>FileID as Guid</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Guid FileID
        {
            get{return this._fileID;}
            set{this._fileID = value;}
        }

        /// <summary>
        /// Public Property IssueID
        /// </summary>
        /// <returns>IssueID as Int64</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Int64 IssueID
        {
            get{return this._issueID;}
            set{this._issueID = value;}
        }

        /// <summary>
        /// Public Property FileName
        /// </summary>
        /// <returns>FileName as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String FileName
        {
            get{return this._fileName;}
            set{this._fileName = value;}
        }

        /// <summary>
        /// Public Property Data
        /// </summary>
        /// <returns>Data as byte[]</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual byte[] Data
        {
            get{return this._data;}
            set{this._data = value;}
        }

        [DataMember()]
        public virtual Issues Issue 
        {
          get { return  _issue;}
          set { _issue = value;}
        }
  
      
    }
 }     
