//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace IssueVision.Domain.Entities
{
    [Serializable()]
    public partial class IssuesList :  Collection<Issues>
    {
        public Issues First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class Issues{
      
        private Int64 _issueID;
        private String _title;
        private Byte _statusID;
        private Nullable<Byte> _subStatusID;
        private String _assignedToID;
        private Byte _issueTypeID;
        private Byte _severity;
        private Byte _priority;
        private String _changedByID;
        private DateTime _lastChange;
        private DateTime _openedDate;
        private String _openedByID;
        private Nullable<Int32> _platformID;
        private Nullable<DateTime> _resolutionDate;
        private Nullable<Byte> _resolutionID;
        private String _resolvedByID;
        private String _description;
        private String _reproSteps;
        private Nullable<Int64> _duplicateID;
        private AttributesList _attributes;
        private FilesList _files;
        private IssuesList _issuesDuplicateID; 
        private Issues _duplicateIDIssues; 
        private IssueTypes _issueType; 
        private Platforms _platform; 
        private Resolutions _resolution; 
        private Statuses _status; 
        private SubStatuses _subStatus; 
        private Users _assignedToIDUsers; 
        private Users _changedByIDUsers; 
        private Users _openedByIDUsers; 
        private Users _resolvedByIDUsers;  

      public Issues() : base()
      {
      }

      public Issues(Int64 issueID, String title, Byte statusID, Nullable<Byte> subStatusID, String assignedToID, Byte issueTypeID, Byte severity, Byte priority, String changedByID, DateTime lastChange, DateTime openedDate, String openedByID, Nullable<Int32> platformID, Nullable<DateTime> resolutionDate, Nullable<Byte> resolutionID, String resolvedByID, String description, String reproSteps, Nullable<Int64> duplicateID) : base()
      {
          
           _issueID = issueID;
           _title = title;
           _statusID = statusID;
           _subStatusID = subStatusID;
           _assignedToID = assignedToID;
           _issueTypeID = issueTypeID;
           _severity = severity;
           _priority = priority;
           _changedByID = changedByID;
           _lastChange = lastChange;
           _openedDate = openedDate;
           _openedByID = openedByID;
           _platformID = platformID;
           _resolutionDate = resolutionDate;
           _resolutionID = resolutionID;
           _resolvedByID = resolvedByID;
           _description = description;
           _reproSteps = reproSteps;
           _duplicateID = duplicateID;
      }
  
    
        /// <summary>
        /// Public Property IssueID
        /// </summary>
        /// <returns>IssueID as Int64</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Int64 IssueID
        {
            get{return this._issueID;}
            set{this._issueID = value;}
        }

        /// <summary>
        /// Public Property Title
        /// </summary>
        /// <returns>Title as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Title
        {
            get{return this._title;}
            set{this._title = value;}
        }

        /// <summary>
        /// Public Property StatusID
        /// </summary>
        /// <returns>StatusID as Byte</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Byte StatusID
        {
            get{return this._statusID;}
            set{this._statusID = value;}
        }

        /// <summary>
        /// Public Property SubStatusID
        /// </summary>
        /// <returns>SubStatusID as Nullable<Byte></returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Nullable<Byte> SubStatusID
        {
            get{return this._subStatusID;}
            set{this._subStatusID = value;}
        }

        /// <summary>
        /// Public Property AssignedToID
        /// </summary>
        /// <returns>AssignedToID as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String AssignedToID
        {
            get{return this._assignedToID;}
            set{this._assignedToID = value;}
        }

        /// <summary>
        /// Public Property IssueTypeID
        /// </summary>
        /// <returns>IssueTypeID as Byte</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Byte IssueTypeID
        {
            get{return this._issueTypeID;}
            set{this._issueTypeID = value;}
        }

        /// <summary>
        /// Public Property Severity
        /// </summary>
        /// <returns>Severity as Byte</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Byte Severity
        {
            get{return this._severity;}
            set{this._severity = value;}
        }

        /// <summary>
        /// Public Property Priority
        /// </summary>
        /// <returns>Priority as Byte</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Byte Priority
        {
            get{return this._priority;}
            set{this._priority = value;}
        }

        /// <summary>
        /// Public Property ChangedByID
        /// </summary>
        /// <returns>ChangedByID as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String ChangedByID
        {
            get{return this._changedByID;}
            set{this._changedByID = value;}
        }

        /// <summary>
        /// Public Property LastChange
        /// </summary>
        /// <returns>LastChange as DateTime</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual DateTime LastChange
        {
            get{return this._lastChange;}
            set{this._lastChange = value;}
        }

        /// <summary>
        /// Public Property OpenedDate
        /// </summary>
        /// <returns>OpenedDate as DateTime</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual DateTime OpenedDate
        {
            get{return this._openedDate;}
            set{this._openedDate = value;}
        }

        /// <summary>
        /// Public Property OpenedByID
        /// </summary>
        /// <returns>OpenedByID as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String OpenedByID
        {
            get{return this._openedByID;}
            set{this._openedByID = value;}
        }

        /// <summary>
        /// Public Property PlatformID
        /// </summary>
        /// <returns>PlatformID as Nullable<Int32></returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Nullable<Int32> PlatformID
        {
            get{return this._platformID;}
            set{this._platformID = value;}
        }

        /// <summary>
        /// Public Property ResolutionDate
        /// </summary>
        /// <returns>ResolutionDate as Nullable<DateTime></returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Nullable<DateTime> ResolutionDate
        {
            get{return this._resolutionDate;}
            set{this._resolutionDate = value;}
        }

        /// <summary>
        /// Public Property ResolutionID
        /// </summary>
        /// <returns>ResolutionID as Nullable<Byte></returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Nullable<Byte> ResolutionID
        {
            get{return this._resolutionID;}
            set{this._resolutionID = value;}
        }

        /// <summary>
        /// Public Property ResolvedByID
        /// </summary>
        /// <returns>ResolvedByID as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String ResolvedByID
        {
            get{return this._resolvedByID;}
            set{this._resolvedByID = value;}
        }

        /// <summary>
        /// Public Property Description
        /// </summary>
        /// <returns>Description as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Description
        {
            get{return this._description;}
            set{this._description = value;}
        }

        /// <summary>
        /// Public Property ReproSteps
        /// </summary>
        /// <returns>ReproSteps as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String ReproSteps
        {
            get{return this._reproSteps;}
            set{this._reproSteps = value;}
        }

        /// <summary>
        /// Public Property DuplicateID
        /// </summary>
        /// <returns>DuplicateID as Nullable<Int64></returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Nullable<Int64> DuplicateID
        {
            get{return this._duplicateID;}
            set{this._duplicateID = value;}
        }

        [DataMember()]
        public virtual AttributesList Attributes 
        {
          get { return  _attributes;}
          set { _attributes = value;}
        }
  
      
        [DataMember()]
        public virtual FilesList Files 
        {
          get { return  _files;}
          set { _files = value;}
        }
  
      
        [DataMember()]
        public virtual IssuesList IssuesDuplicateID 
        {
          get { return  _issuesDuplicateID;}
          set { _issuesDuplicateID = value;}
        }
  
      
        [DataMember()]
        public virtual Issues DuplicateIDIssues 
        {
          get { return  _duplicateIDIssues;}
          set { _duplicateIDIssues = value;}
        }
  
      
        [DataMember()]
        public virtual IssueTypes IssueType 
        {
          get { return  _issueType;}
          set { _issueType = value;}
        }
  
      
        [DataMember()]
        public virtual Platforms Platform 
        {
          get { return  _platform;}
          set { _platform = value;}
        }
  
      
        [DataMember()]
        public virtual Resolutions Resolution 
        {
          get { return  _resolution;}
          set { _resolution = value;}
        }
  
      
        [DataMember()]
        public virtual Statuses Status 
        {
          get { return  _status;}
          set { _status = value;}
        }
  
      
        [DataMember()]
        public virtual SubStatuses SubStatus 
        {
          get { return  _subStatus;}
          set { _subStatus = value;}
        }
  
      
        [DataMember()]
        public virtual Users AssignedToIDUsers 
        {
          get { return  _assignedToIDUsers;}
          set { _assignedToIDUsers = value;}
        }
  
      
        [DataMember()]
        public virtual Users ChangedByIDUsers 
        {
          get { return  _changedByIDUsers;}
          set { _changedByIDUsers = value;}
        }
  
      
        [DataMember()]
        public virtual Users OpenedByIDUsers 
        {
          get { return  _openedByIDUsers;}
          set { _openedByIDUsers = value;}
        }
  
      
        [DataMember()]
        public virtual Users ResolvedByIDUsers 
        {
          get { return  _resolvedByIDUsers;}
          set { _resolvedByIDUsers = value;}
        }
  
      
    }
 }     
