//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace IssueVision.Domain.Entities
{
    [Serializable()]
    public partial class IssueTypesList :  Collection<IssueTypes>
    {
        public IssueTypes First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class IssueTypes{
      
        private Byte _issueTypeID;
        private String _name;
        private IssuesList _issues;  

      public IssueTypes() : base()
      {
      }

      public IssueTypes(Byte issueTypeID, String name) : base()
      {
          
           _issueTypeID = issueTypeID;
           _name = name;
      }
  
    
        /// <summary>
        /// Public Property IssueTypeID
        /// </summary>
        /// <returns>IssueTypeID as Byte</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Byte IssueTypeID
        {
            get{return this._issueTypeID;}
            set{this._issueTypeID = value;}
        }

        /// <summary>
        /// Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Name
        {
            get{return this._name;}
            set{this._name = value;}
        }

        [DataMember()]
        public virtual IssuesList Issues 
        {
          get { return  _issues;}
          set { _issues = value;}
        }
  
      
    }
 }     
