//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace IssueVision.Domain.Entities
{
    [Serializable()]
    public partial class ResolutionsList :  Collection<Resolutions>
    {
        public Resolutions First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class Resolutions{
      
        private Byte _resolutionID;
        private String _name;
        private IssuesList _issues;  

      public Resolutions() : base()
      {
      }

      public Resolutions(Byte resolutionID, String name) : base()
      {
          
           _resolutionID = resolutionID;
           _name = name;
      }
  
    
        /// <summary>
        /// Public Property ResolutionID
        /// </summary>
        /// <returns>ResolutionID as Byte</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Byte ResolutionID
        {
            get{return this._resolutionID;}
            set{this._resolutionID = value;}
        }

        /// <summary>
        /// Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Name
        {
            get{return this._name;}
            set{this._name = value;}
        }

        [DataMember()]
        public virtual IssuesList Issues 
        {
          get { return  _issues;}
          set { _issues = value;}
        }
  
      
    }
 }     
