//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace IssueVision.Domain.Entities
{
    [Serializable()]
    public partial class SecurityQuestionsList :  Collection<SecurityQuestions>
    {
        public SecurityQuestions First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class SecurityQuestions{
      
        private String _passwordQuestion;
        private UsersList _users;  

      public SecurityQuestions() : base()
      {
      }

      public SecurityQuestions(String passwordQuestion) : base()
      {
          
           _passwordQuestion = passwordQuestion;
      }
  
    
        /// <summary>
        /// Public Property PasswordQuestion
        /// </summary>
        /// <returns>PasswordQuestion as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String PasswordQuestion
        {
            get{return this._passwordQuestion;}
            set{this._passwordQuestion = value;}
        }

        [DataMember()]
        public virtual UsersList Users 
        {
          get { return  _users;}
          set { _users = value;}
        }
  
      
    }
 }     
