//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace IssueVision.Domain.Entities
{
    [Serializable()]
    public partial class StatusesList :  Collection<Statuses>
    {
        public Statuses First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class Statuses{
      
        private Byte _statusID;
        private String _name;
        private IssuesList _issues;  

      public Statuses() : base()
      {
      }

      public Statuses(Byte statusID, String name) : base()
      {
          
           _statusID = statusID;
           _name = name;
      }
  
    
        /// <summary>
        /// Public Property StatusID
        /// </summary>
        /// <returns>StatusID as Byte</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Byte StatusID
        {
            get{return this._statusID;}
            set{this._statusID = value;}
        }

        /// <summary>
        /// Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Name
        {
            get{return this._name;}
            set{this._name = value;}
        }

        [DataMember()]
        public virtual IssuesList Issues 
        {
          get { return  _issues;}
          set { _issues = value;}
        }
  
      
    }
 }     
