//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace IssueVision.Domain.Entities
{
    [Serializable()]
    public partial class UsersList :  Collection<Users>
    {
        public Users First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class Users{
      
        private String _name;
        private String _firstName;
        private String _lastName;
        private String _email;
        private String _passwordHash;
        private String _passwordSalt;
        private String _passwordQuestion;
        private String _passwordAnswerHash;
        private String _passwordAnswerSalt;
        private String _userType;
        private Byte _profileReset;
        private IssuesList _issuesAssignedToID;
        private IssuesList _issuesChangedByID;
        private IssuesList _issuesOpenedByID;
        private IssuesList _issuesResolvedByID; 
        private SecurityQuestions _securityQuestion;  

      public Users() : base()
      {
      }

      public Users(String name, String firstName, String lastName, String email, String passwordHash, String passwordSalt, String passwordQuestion, String passwordAnswerHash, String passwordAnswerSalt, String userType, Byte profileReset) : base()
      {
          
           _name = name;
           _firstName = firstName;
           _lastName = lastName;
           _email = email;
           _passwordHash = passwordHash;
           _passwordSalt = passwordSalt;
           _passwordQuestion = passwordQuestion;
           _passwordAnswerHash = passwordAnswerHash;
           _passwordAnswerSalt = passwordAnswerSalt;
           _userType = userType;
           _profileReset = profileReset;
      }
  
    
        /// <summary>
        /// Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Name
        {
            get{return this._name;}
            set{this._name = value;}
        }

        /// <summary>
        /// Public Property FirstName
        /// </summary>
        /// <returns>FirstName as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String FirstName
        {
            get{return this._firstName;}
            set{this._firstName = value;}
        }

        /// <summary>
        /// Public Property LastName
        /// </summary>
        /// <returns>LastName as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String LastName
        {
            get{return this._lastName;}
            set{this._lastName = value;}
        }

        /// <summary>
        /// Public Property Email
        /// </summary>
        /// <returns>Email as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Email
        {
            get{return this._email;}
            set{this._email = value;}
        }

        /// <summary>
        /// Public Property PasswordHash
        /// </summary>
        /// <returns>PasswordHash as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String PasswordHash
        {
            get{return this._passwordHash;}
            set{this._passwordHash = value;}
        }

        /// <summary>
        /// Public Property PasswordSalt
        /// </summary>
        /// <returns>PasswordSalt as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String PasswordSalt
        {
            get{return this._passwordSalt;}
            set{this._passwordSalt = value;}
        }

        /// <summary>
        /// Public Property PasswordQuestion
        /// </summary>
        /// <returns>PasswordQuestion as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String PasswordQuestion
        {
            get{return this._passwordQuestion;}
            set{this._passwordQuestion = value;}
        }

        /// <summary>
        /// Public Property PasswordAnswerHash
        /// </summary>
        /// <returns>PasswordAnswerHash as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String PasswordAnswerHash
        {
            get{return this._passwordAnswerHash;}
            set{this._passwordAnswerHash = value;}
        }

        /// <summary>
        /// Public Property PasswordAnswerSalt
        /// </summary>
        /// <returns>PasswordAnswerSalt as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String PasswordAnswerSalt
        {
            get{return this._passwordAnswerSalt;}
            set{this._passwordAnswerSalt = value;}
        }

        /// <summary>
        /// Public Property UserType
        /// </summary>
        /// <returns>UserType as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String UserType
        {
            get{return this._userType;}
            set{this._userType = value;}
        }

        /// <summary>
        /// Public Property ProfileReset
        /// </summary>
        /// <returns>ProfileReset as Byte</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Byte ProfileReset
        {
            get{return this._profileReset;}
            set{this._profileReset = value;}
        }

        [DataMember()]
        public virtual IssuesList IssuesAssignedToID 
        {
          get { return  _issuesAssignedToID;}
          set { _issuesAssignedToID = value;}
        }
  
      
        [DataMember()]
        public virtual IssuesList IssuesChangedByID 
        {
          get { return  _issuesChangedByID;}
          set { _issuesChangedByID = value;}
        }
  
      
        [DataMember()]
        public virtual IssuesList IssuesOpenedByID 
        {
          get { return  _issuesOpenedByID;}
          set { _issuesOpenedByID = value;}
        }
  
      
        [DataMember()]
        public virtual IssuesList IssuesResolvedByID 
        {
          get { return  _issuesResolvedByID;}
          set { _issuesResolvedByID = value;}
        }
  
      
        [DataMember()]
        public virtual SecurityQuestions SecurityQuestion 
        {
          get { return  _securityQuestion;}
          set { _securityQuestion = value;}
        }
  
      
    }
 }     
