'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data

Namespace IssueVision.Data.DbCommandProvider
    Public Interface IDbPlatformsCommandProvider
        ReadOnly Property PlatformsDbConnectionHolder() As DbConnectionHolder
        ReadOnly Property DbConnectionName As String
        Function GetGetDataDbCommand() As IDbCommand
        Function GetUpdateDbCommand( ByVal platformID As Int32,  ByVal browser As String,  ByVal browserVersion As String,  ByVal oS As String,  ByVal oSVersion As String,  ByVal language As String,  ByVal processor As String) As IDbCommand
        Function GetInsertDbCommand( ByVal platformID As Int32,  ByVal browser As String,  ByVal browserVersion As String,  ByVal oS As String,  ByVal oSVersion As String,  ByVal language As String,  ByVal processor As String) As IDbCommand
        Function GetDeleteDbCommand( ByVal platformID As Int32) As IDbCommand
        Function GetGetDataPageableDbCommand( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetRowCountDbCommand() As IDbCommand
        Function GetGetDataByPlatformIDDbCommand( ByVal platformID As Int32) As IDbCommand

    End Interface
End Namespace
