'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data

Namespace IssueVision.Data.DbCommandProvider
    Public Interface IDbStatusesCommandProvider
        ReadOnly Property StatusesDbConnectionHolder() As DbConnectionHolder
        ReadOnly Property DbConnectionName As String
        Function GetGetDataDbCommand() As IDbCommand
        Function GetUpdateDbCommand( ByVal statusID As Byte,  ByVal name As String) As IDbCommand
        Function GetInsertDbCommand( ByVal statusID As Byte,  ByVal name As String) As IDbCommand
        Function GetDeleteDbCommand( ByVal statusID As Byte) As IDbCommand
        Function GetGetDataPageableDbCommand( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetRowCountDbCommand() As IDbCommand
        Function GetGetDataByStatusIDDbCommand( ByVal statusID As Byte) As IDbCommand

    End Interface
End Namespace
