//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using IssueVision.Data.DbCommandProvider;
using IssueVision.Data.Repository;
using IssueVision.Domain.Entities;

namespace IssueVision.Web.UI.Controllers.Api
{
    public class IssueTypesApiController : ApiController
    {
        private readonly IIssueTypesRepository _dbRepository;

        public IssueTypesApiController(IIssueTypesRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
   
                [Route("api/issueTypes/all", Name = "IssueTypesGetDataRoute")]
        [HttpGet]
        public IQueryable<IssueTypes> GetData() 
        {
            return _dbRepository.GetData().AsQueryable();
        }

        [Route("api/issueTypes", Name = "IssueTypesUpdateRoute")]
        [HttpPut]
        public void Update(IssueTypes issueTypes)
        {
            _dbRepository.Update(issueTypes.IssueTypeID,  (string)issueTypes.Name);
          }

        [Route("api/issueTypes", Name = "IssueTypesInsertRoute")]
        [HttpPost]
        public Byte Insert(IssueTypes issueTypes)
        {
             return _dbRepository.Insert(issueTypes.IssueTypeID,  (string)issueTypes.Name);
          }

        [Route("api/issueTypes", Name = "IssueTypesDeleteRoute")]
        [HttpDelete]
        public HttpResponseMessage Delete(Byte issueTypeID)
        {
            try
            {
                 _dbRepository.Delete(issueTypeID);
                 return Request.CreateResponse(HttpStatusCode.OK);
            }
                 catch (Exception)
            {
                 return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        [Route("api/issueTypes", Name = "IssueTypesGetDataPageableRoute")]
        [HttpGet]
        public  HttpResponseMessage  GetDataPageable(String sortExpression, Int32 page, Int32 pageSize) 
        {
              if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results =_dbRepository.GetDataPageable(sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetRowCount();
            var pagedResults = PagedResultHelper.CreatePagedResult(Request, "IssueTypesGetDataPageableRoute", page,
                pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }

        [Route("api/issueTypes/{issueTypeID}", Name = "IssueTypesGetDataByIssueTypeIDRoute")]
        [HttpGet]
        public IQueryable<IssueTypes> GetDataByIssueTypeID(Byte issueTypeID) 
        {
            return _dbRepository.GetDataByIssueTypeID(issueTypeID).AsQueryable();
        }


    }
}
