//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using IssueVision.Data.DbCommandProvider;
using IssueVision.Data.Repository;
using IssueVision.Domain.Entities;

namespace IssueVision.Web.UI.Controllers.Api
{
    public class StatusesApiController : ApiController
    {
        private readonly IStatusesRepository _dbRepository;

        public StatusesApiController(IStatusesRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
   
                [Route("api/statuses/all", Name = "StatusesGetDataRoute")]
        [HttpGet]
        public IQueryable<Statuses> GetData() 
        {
            return _dbRepository.GetData().AsQueryable();
        }

        [Route("api/statuses", Name = "StatusesUpdateRoute")]
        [HttpPut]
        public void Update(Statuses statuses)
        {
            _dbRepository.Update(statuses.StatusID,  (string)statuses.Name);
          }

        [Route("api/statuses", Name = "StatusesInsertRoute")]
        [HttpPost]
        public Byte Insert(Statuses statuses)
        {
             return _dbRepository.Insert(statuses.StatusID,  (string)statuses.Name);
          }

        [Route("api/statuses", Name = "StatusesDeleteRoute")]
        [HttpDelete]
        public HttpResponseMessage Delete(Byte statusID)
        {
            try
            {
                 _dbRepository.Delete(statusID);
                 return Request.CreateResponse(HttpStatusCode.OK);
            }
                 catch (Exception)
            {
                 return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        [Route("api/statuses", Name = "StatusesGetDataPageableRoute")]
        [HttpGet]
        public  HttpResponseMessage  GetDataPageable(String sortExpression, Int32 page, Int32 pageSize) 
        {
              if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results =_dbRepository.GetDataPageable(sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetRowCount();
            var pagedResults = PagedResultHelper.CreatePagedResult(Request, "StatusesGetDataPageableRoute", page,
                pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }

        [Route("api/statuses/{statusID}", Name = "StatusesGetDataByStatusIDRoute")]
        [HttpGet]
        public IQueryable<Statuses> GetDataByStatusID(Byte statusID) 
        {
            return _dbRepository.GetDataByStatusID(statusID).AsQueryable();
        }


    }
}
