//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using IssueVision.Data.DbCommandProvider;
using IssueVision.Data.Repository;
using IssueVision.Domain.Entities;

namespace IssueVision.Web.UI.Controllers.Api
{
    public class SubStatusesApiController : ApiController
    {
        private readonly ISubStatusesRepository _dbRepository;

        public SubStatusesApiController(ISubStatusesRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
   
                [Route("api/subStatuses/all", Name = "SubStatusesGetDataRoute")]
        [HttpGet]
        public IQueryable<SubStatuses> GetData() 
        {
            return _dbRepository.GetData().AsQueryable();
        }

        [Route("api/subStatuses", Name = "SubStatusesUpdateRoute")]
        [HttpPut]
        public void Update(SubStatuses subStatuses)
        {
            _dbRepository.Update(subStatuses.SubStatusId,  (string)subStatuses.Name);
          }

        [Route("api/subStatuses", Name = "SubStatusesInsertRoute")]
        [HttpPost]
        public Byte Insert(SubStatuses subStatuses)
        {
             return _dbRepository.Insert(subStatuses.SubStatusId,  (string)subStatuses.Name);
          }

        [Route("api/subStatuses", Name = "SubStatusesDeleteRoute")]
        [HttpDelete]
        public HttpResponseMessage Delete(Byte subStatusId)
        {
            try
            {
                 _dbRepository.Delete(subStatusId);
                 return Request.CreateResponse(HttpStatusCode.OK);
            }
                 catch (Exception)
            {
                 return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        [Route("api/subStatuses", Name = "SubStatusesGetDataPageableRoute")]
        [HttpGet]
        public  HttpResponseMessage  GetDataPageable(String sortExpression, Int32 page, Int32 pageSize) 
        {
              if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results =_dbRepository.GetDataPageable(sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetRowCount();
            var pagedResults = PagedResultHelper.CreatePagedResult(Request, "SubStatusesGetDataPageableRoute", page,
                pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }

        [Route("api/subStatuses", Name = "SubStatusesGetDataBySubStatusIdRoute")]
        [HttpGet]
        public IQueryable<SubStatuses> GetDataBySubStatusId(Byte subStatusId) 
        {
            return _dbRepository.GetDataBySubStatusId(subStatusId).AsQueryable();
        }


    }
}
