//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using IssueVision.Data.DbCommandProvider;
using IssueVision.Data.Repository;
using IssueVision.Domain.Entities;

namespace IssueVision.Web.UI.Controllers.Api
{
    public class UsersApiController : ApiController
    {
        private readonly IUsersRepository _dbRepository;

        public UsersApiController(IUsersRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
   
                [Route("api/users/all", Name = "UsersGetDataRoute")]
        [HttpGet]
        public IQueryable<Users> GetData() 
        {
            return _dbRepository.GetData().AsQueryable();
        }

        [Route("api/users", Name = "UsersUpdateRoute")]
        [HttpPut]
        public void Update(Users users)
        {
            _dbRepository.Update( (string)users.Name,  (string)users.FirstName,  (string)users.LastName, users.Email,  (string)users.PasswordHash,  (string)users.PasswordSalt,  (string)users.PasswordQuestion,  (string)users.PasswordAnswerHash,  (string)users.PasswordAnswerSalt,  (string)users.UserType, users.ProfileReset);
          }

        [Route("api/users", Name = "UsersInsertRoute")]
        [HttpPost]
        public String Insert(Users users)
        {
             return _dbRepository.Insert( (string)users.Name,  (string)users.FirstName,  (string)users.LastName, users.Email,  (string)users.PasswordHash,  (string)users.PasswordSalt,  (string)users.PasswordQuestion,  (string)users.PasswordAnswerHash,  (string)users.PasswordAnswerSalt,  (string)users.UserType, users.ProfileReset);
          }

        [Route("api/users", Name = "UsersDeleteRoute")]
        [HttpDelete]
        public HttpResponseMessage Delete(String name)
        {
            try
            {
                 _dbRepository.Delete(name);
                 return Request.CreateResponse(HttpStatusCode.OK);
            }
                 catch (Exception)
            {
                 return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        [Route("api/users", Name = "UsersGetDataPageableRoute")]
        [HttpGet]
        public  HttpResponseMessage  GetDataPageable(String sortExpression, Int32 page, Int32 pageSize) 
        {
              if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results =_dbRepository.GetDataPageable(sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetRowCount();
            var pagedResults = PagedResultHelper.CreatePagedResult(Request, "UsersGetDataPageableRoute", page,
                pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }

        [Route("api/users", Name = "UsersGetDataByNameRoute")]
        [HttpGet]
        public IQueryable<Users> GetDataByName(String name) 
        {
            return _dbRepository.GetDataByName(name).AsQueryable();
        }

        [Route("api/securityQuestions/{passwordQuestion}/users/all", Name = "UsersGetDataByPasswordQuestionRoute")]
        [HttpGet]
        public IQueryable<Users> GetDataByPasswordQuestion(String passwordQuestion) 
        {
            return _dbRepository.GetDataByPasswordQuestion(passwordQuestion).AsQueryable();
        }

        [Route("api/securityQuestions/{passwordQuestion}/users", Name = "UsersGetDataByPasswordQuestionPageableRoute")]
        [HttpGet]
        public  HttpResponseMessage  GetDataByPasswordQuestionPageable(String passwordQuestion, String sortExpression, Int32 page, Int32 pageSize) 
        {
              if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results =_dbRepository.GetDataByPasswordQuestionPageable(passwordQuestion, sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetDataByPasswordQuestionRowCount(passwordQuestion);
            var pagedResults = PagedResultHelper.CreatePagedResult(Request, "UsersGetDataByPasswordQuestionPageableRoute", page,
                pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }


    }
}
