'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities
Imports IssueVision.Data.DbCommandProvider
Imports System.Collections.ObjectModel

  
Namespace IssueVision.Data.Repository    
    
    <Global.System.ComponentModel.DataObjectAttribute(true)>  _
    Public Class DbFilesRepository
        Implements IFilesRepository
        Implements IDisposable

        Private ReadOnly _dbFilesCommandProvider As IDbFilesCommandProvider
        Private _dbConnHolder As DbConnectionHolder = Nothing

        Public Sub New(ByVal dbFilesCommandProvider As IDbFilesCommandProvider)
            _dbFilesCommandProvider = dbFilesCommandProvider
            _dbConnHolder =_dbFilesCommandProvider.FilesDbConnectionHolder
        End Sub

      
    ''' <summary>
    ''' Selects one or more records from the Files table 
    ''' </summary>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], true)> _ 
    Public Function GetData()  as ICollection(Of Files) Implements IFilesRepository.GetData
        Dim command As IDbCommand = _dbFilesCommandProvider.GetGetDataDbCommand()
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Files)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Files( CType(reader("FileID"), Guid) , CLng(reader("IssueID")),  reader.GetString("FileName") ,  CType(reader("Data"),Byte()) )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Updates one or more records from the Files table 
    ''' </summary>
   ''' <param name="FileID"></param>
   ''' <param name="IssueID"></param>
   ''' <param name="FileName"></param>
   ''' <param name="Data"></param>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, true)> _ 
    Public Sub Update( ByVal fileID As Guid,  ByVal issueID As Int64,  ByVal fileName As String,  ByVal data As Byte())  Implements IFilesRepository.Update
        Dim command As IDbCommand = _dbFilesCommandProvider.GetUpdateDbCommand(FileID, IssueID, FileName, Data)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
          Command.ExecuteNonQuery
            _dbConnHolder.Close()
    End Sub
  
    ''' <summary>
    ''' Updates one or more records from the Files table 
    ''' </summary>
    ''' <param name="Files"></param>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, False)> _ 
    Public Sub Update(ByVal files as Files)  Implements IFilesRepository.Update
             With Files
Update( CType(.FileID, Guid), .IssueID,  CStr(.FileName),  CType(.Data,Byte()))
       End With

    End Sub
  
    ''' <summary>
    ''' Inserts an entity of Files into the database.
    ''' </summary>
   ''' <param name="FileID"></param>
   ''' <param name="IssueID"></param>
   ''' <param name="FileName"></param>
   ''' <param name="Data"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Insert, true)> _ 
    Public Function Insert( ByVal fileID As Guid,  ByVal issueID As Int64,  ByVal fileName As String,  ByVal data As Byte())  as Guid Implements IFilesRepository.Insert
        Dim command As IDbCommand = _dbFilesCommandProvider.GetInsertDbCommand(FileID, IssueID, FileName, Data)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
            Dim returnValue As Guid = New Guid(command.ExecuteScalar().ToString)
            _dbConnHolder.Close()
            Return returnValue 

    End Function
  
    ''' <summary>
    ''' Inserts an entity of Files into the database.
    ''' </summary>
    ''' <param name="Files"></param>
    ''' <returns></returns>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Insert, False)> _ 
    Public Function Insert(ByVal files as Files)  as Guid Implements IFilesRepository.Insert
             With Files
 Return Insert( CType(.FileID, Guid), .IssueID,  CStr(.FileName),  CType(.Data,Byte()))
       End With

    End Function
  
    ''' <summary>
    ''' Deletes one or more records from the Files table 
    ''' </summary>
   ''' <param name="FileID"></param>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Delete, true)> _ 
    Public Sub Delete( ByVal fileID As Guid)  Implements IFilesRepository.Delete
        Dim command As IDbCommand = _dbFilesCommandProvider.GetDeleteDbCommand(FileID)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
          Command.ExecuteNonQuery
            _dbConnHolder.Close()
    End Sub
  
    ''' <summary>
    ''' Deletes one or more records from the Files table 
    ''' </summary>
    ''' <param name="Files"></param>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Delete, False)> _ 
    Public Sub Delete(ByVal files as Files)  Implements IFilesRepository.Delete
             With Files
Delete( CType(.FileID, Guid))
       End With

    End Sub
  
    ''' <summary>
    ''' Function GetDataPageable returns a IDataReader populated with a subset of data from Files
    ''' </summary>
   ''' <param name="sortExpression"></param>
   ''' <param name="page"></param>
   ''' <param name="pageSize"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Files) Implements IFilesRepository.GetDataPageable
        Dim command As IDbCommand = _dbFilesCommandProvider.GetGetDataPageableDbCommand(sortExpression, page, pageSize)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Files)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Files( CType(reader("FileID"), Guid) , CLng(reader("IssueID")),  reader.GetString("FileName") ,  CType(reader("Data"),Byte()) )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetRowCount returns the row count for Files
    ''' </summary>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetRowCount()  as Int32 Implements IFilesRepository.GetRowCount
        Dim command As IDbCommand = _dbFilesCommandProvider.GetGetRowCountDbCommand()
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim returnValue As Int32  = Convert.ToInt32(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue 

    End Function
  
    ''' <summary>
    ''' Function GetDataByFileID returns a IDataReader for Files
    ''' </summary>
   ''' <param name="FileID"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetDataByFileID( ByVal fileID As Guid)  as ICollection(Of Files) Implements IFilesRepository.GetDataByFileID
        Dim command As IDbCommand = _dbFilesCommandProvider.GetGetDataByFileIDDbCommand(FileID)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Files)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Files( CType(reader("FileID"), Guid) , CLng(reader("IssueID")),  reader.GetString("FileName") ,  CType(reader("Data"),Byte()) )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetDataByIssueID returns a IDataReader for Files
    ''' </summary>
   ''' <param name="IssueID"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetDataByIssueID( ByVal issueID As Int64)  as ICollection(Of Files) Implements IFilesRepository.GetDataByIssueID
        Dim command As IDbCommand = _dbFilesCommandProvider.GetGetDataByIssueIDDbCommand(IssueID)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Files)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Files( CType(reader("FileID"), Guid) , CLng(reader("IssueID")),  reader.GetString("FileName") ,  CType(reader("Data"),Byte()) )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetDataByIssueIDPageable returns a IDataReader populated with a subset of data from Files
    ''' </summary>
   ''' <param name="IssueID"></param>
   ''' <param name="sortExpression"></param>
   ''' <param name="page"></param>
   ''' <param name="pageSize"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetDataByIssueIDPageable( ByVal issueID As Int64,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Files) Implements IFilesRepository.GetDataByIssueIDPageable
        Dim command As IDbCommand = _dbFilesCommandProvider.GetGetDataByIssueIDPageableDbCommand(IssueID, sortExpression, page, pageSize)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Files)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Files( CType(reader("FileID"), Guid) , CLng(reader("IssueID")),  reader.GetString("FileName") ,  CType(reader("Data"),Byte()) )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetRowCount returns the row count for Files
    ''' </summary>
   ''' <param name="IssueID"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetDataByIssueIDRowCount( ByVal issueID As Int64)  as Int32 Implements IFilesRepository.GetDataByIssueIDRowCount
        Dim command As IDbCommand = _dbFilesCommandProvider.GetGetDataByIssueIDRowCountDbCommand(IssueID)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim returnValue As Int32  = Convert.ToInt32(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue 

    End Function
   
  
#Region "IDisposable Support"
        Private disposedValue As Boolean
        Protected Overridable Sub Dispose(disposing As Boolean)
            If Not Me.disposedValue Then
                If disposing Then
                    Select Case _dbConnHolder.Connection.State
                        Case ConnectionState.Open
                            _dbConnHolder.Close()
                    End Select
                    _dbConnHolder = Nothing
                End If

            End If
            Me.disposedValue = True
        End Sub

        Public Sub Dispose() Implements IDisposable.Dispose
            Dispose(True)
            GC.SuppressFinalize(Me)
        End Sub
#End Region
 
  End Class 
End NameSpace
