'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Collections.Generic
Imports IssueVision.Data
Imports IssueVision.Domain.Entities
Imports IssueVision.Data.DbCommandProvider
Imports System.Collections.ObjectModel

  
Namespace IssueVision.Data.Repository    
    
    <Global.System.ComponentModel.DataObjectAttribute(true)>  _
    Public Class DbSubStatusesRepository
        Implements ISubStatusesRepository
        Implements IDisposable

        Private ReadOnly _dbSubStatusesCommandProvider As IDbSubStatusesCommandProvider
        Private _dbConnHolder As DbConnectionHolder = Nothing

        Public Sub New(ByVal dbSubStatusesCommandProvider As IDbSubStatusesCommandProvider)
            _dbSubStatusesCommandProvider = dbSubStatusesCommandProvider
            _dbConnHolder =_dbSubStatusesCommandProvider.SubStatusesDbConnectionHolder
        End Sub

      
    ''' <summary>
    ''' Selects one or more records from the SubStatuses table 
    ''' </summary>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], true)> _ 
    Public Function GetData()  as ICollection(Of SubStatuses) Implements ISubStatusesRepository.GetData
        Dim command As IDbCommand = _dbSubStatusesCommandProvider.GetGetDataDbCommand()
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of SubStatuses)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New SubStatuses(reader("SubStatusId"),  reader.GetString("Name") )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Updates one or more records from the SubStatuses table 
    ''' </summary>
   ''' <param name="SubStatusId"></param>
   ''' <param name="Name"></param>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, true)> _ 
    Public Sub Update( ByVal subStatusId As Byte,  ByVal name As String)  Implements ISubStatusesRepository.Update
        Dim command As IDbCommand = _dbSubStatusesCommandProvider.GetUpdateDbCommand(SubStatusId, Name)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
          Command.ExecuteNonQuery
            _dbConnHolder.Close()
    End Sub
  
    ''' <summary>
    ''' Updates one or more records from the SubStatuses table 
    ''' </summary>
    ''' <param name="SubStatuses"></param>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, False)> _ 
    Public Sub Update(ByVal subStatuses as SubStatuses)  Implements ISubStatusesRepository.Update
             With SubStatuses
Update(.SubStatusId,  CStr(.Name))
       End With

    End Sub
  
    ''' <summary>
    ''' Inserts an entity of SubStatuses into the database.
    ''' </summary>
   ''' <param name="SubStatusId"></param>
   ''' <param name="Name"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Insert, true)> _ 
    Public Function Insert( ByVal subStatusId As Byte,  ByVal name As String)  as Byte Implements ISubStatusesRepository.Insert
        Dim command As IDbCommand = _dbSubStatusesCommandProvider.GetInsertDbCommand(SubStatusId, Name)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim returnValue As Byte  = Convert.ToByte(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue 

    End Function
  
    ''' <summary>
    ''' Inserts an entity of SubStatuses into the database.
    ''' </summary>
    ''' <param name="SubStatuses"></param>
    ''' <returns></returns>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Insert, False)> _ 
    Public Function Insert(ByVal subStatuses as SubStatuses)  as Byte Implements ISubStatusesRepository.Insert
             With SubStatuses
 Return Insert(.SubStatusId,  CStr(.Name))
       End With

    End Function
  
    ''' <summary>
    ''' Deletes one or more records from the SubStatuses table 
    ''' </summary>
   ''' <param name="SubStatusId"></param>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Delete, true)> _ 
    Public Sub Delete( ByVal subStatusId As Byte)  Implements ISubStatusesRepository.Delete
        Dim command As IDbCommand = _dbSubStatusesCommandProvider.GetDeleteDbCommand(SubStatusId)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
          Command.ExecuteNonQuery
            _dbConnHolder.Close()
    End Sub
  
    ''' <summary>
    ''' Deletes one or more records from the SubStatuses table 
    ''' </summary>
    ''' <param name="SubStatuses"></param>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Delete, False)> _ 
    Public Sub Delete(ByVal subStatuses as SubStatuses)  Implements ISubStatusesRepository.Delete
             With SubStatuses
Delete(.SubStatusId)
       End With

    End Sub
  
    ''' <summary>
    ''' Function GetDataPageable returns a IDataReader populated with a subset of data from SubStatuses
    ''' </summary>
   ''' <param name="sortExpression"></param>
   ''' <param name="page"></param>
   ''' <param name="pageSize"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of SubStatuses) Implements ISubStatusesRepository.GetDataPageable
        Dim command As IDbCommand = _dbSubStatusesCommandProvider.GetGetDataPageableDbCommand(sortExpression, page, pageSize)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of SubStatuses)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New SubStatuses(reader("SubStatusId"),  reader.GetString("Name") )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetRowCount returns the row count for SubStatuses
    ''' </summary>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetRowCount()  as Int32 Implements ISubStatusesRepository.GetRowCount
        Dim command As IDbCommand = _dbSubStatusesCommandProvider.GetGetRowCountDbCommand()
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim returnValue As Int32  = Convert.ToInt32(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue 

    End Function
  
    ''' <summary>
    ''' Function GetDataBySubStatusId returns a IDataReader for SubStatuses
    ''' </summary>
   ''' <param name="SubStatusId"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetDataBySubStatusId( ByVal subStatusId As Byte)  as ICollection(Of SubStatuses) Implements ISubStatusesRepository.GetDataBySubStatusId
        Dim command As IDbCommand = _dbSubStatusesCommandProvider.GetGetDataBySubStatusIdDbCommand(SubStatusId)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of SubStatuses)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New SubStatuses(reader("SubStatusId"),  reader.GetString("Name") )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
   
  
#Region "IDisposable Support"
        Private disposedValue As Boolean
        Protected Overridable Sub Dispose(disposing As Boolean)
            If Not Me.disposedValue Then
                If disposing Then
                    Select Case _dbConnHolder.Connection.State
                        Case ConnectionState.Open
                            _dbConnHolder.Close()
                    End Select
                    _dbConnHolder = Nothing
                End If

            End If
            Me.disposedValue = True
        End Sub

        Public Sub Dispose() Implements IDisposable.Dispose
            Dispose(True)
            GC.SuppressFinalize(Me)
        End Sub
#End Region
 
  End Class 
End NameSpace
